<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="en_GB" sourcelanguage="en_US">
<context>
    <name>Colors</name>
    <message>
        <source>red</source>
        <translation></translation>
    </message>
    <message>
        <source>green</source>
        <translation></translation>
    </message>
    <message>
        <source>blue</source>
        <translation></translation>
    </message>
    <message>
        <source>white</source>
        <translation></translation>
    </message>
    <message>
        <source>gray</source>
        <translation>grey</translation>
    </message>
    <message>
        <source>black</source>
        <translation></translation>
    </message>
    <message>
        <source>yellow</source>
        <translation></translation>
    </message>
    <message>
        <source>orange</source>
        <translation></translation>
    </message>
    <message>
        <source>brown</source>
        <translation></translation>
    </message>
    <message>
        <source>pink</source>
        <translation></translation>
    </message>
    <message>
        <source>violet</source>
        <translation></translation>
    </message>
</context>
<context>
    <name>LessonMenu</name>
    <message>
        <source>Read the first letter</source>
        <translation></translation>
    </message>
    <message>
        <source>Read words</source>
        <translation></translation>
    </message>
    <message>
        <source>Count to 5</source>
        <translation></translation>
    </message>
    <message>
        <source>Count and read to 5</source>
        <translation></translation>
    </message>
    <message>
        <source>Count to 20</source>
        <translation></translation>
    </message>
    <message>
        <source>Count and read to 20</source>
        <translation></translation>
    </message>
    <message>
        <source>Read the clock, full hours</source>
        <translation></translation>
    </message>
    <message>
        <source>Read the clock, half hours</source>
        <translation></translation>
    </message>
    <message>
        <source>Read the clock</source>
        <translation></translation>
    </message>
    <message>
        <source>Read</source>
        <translation></translation>
    </message>
    <message>
        <source>Count</source>
        <translation></translation>
    </message>
    <message>
        <source>Clock</source>
        <translation></translation>
    </message>
    <message>
        <source>Music</source>
        <translation></translation>
    </message>
    <message>
        <source>Read notes, whole step</source>
        <translation></translation>
    </message>
    <message>
        <source>Read notes, half-step</source>
        <translation></translation>
    </message>
    <message>
        <source>Mixed</source>
        <translation></translation>
    </message>
    <message>
        <source>Mixed lessons, easy</source>
        <translation></translation>
    </message>
    <message>
        <source>Mixed lessons, medium</source>
        <translation></translation>
    </message>
    <message>
        <source>Mixed lessons, hard</source>
        <translation></translation>
    </message>
    <message>
        <source>Color</source>
        <translation></translation>
    </message>
    <message>
        <source>Recognize the color</source>
        <translation></translation>
    </message>
</context>
<context>
    <name>Notes</name>
    <message>
        <source>C</source>
        <translation></translation>
    </message>
    <message>
        <source>C sharp</source>
        <translation></translation>
    </message>
    <message>
        <source>D flat</source>
        <translation></translation>
    </message>
    <message>
        <source>D</source>
        <translation></translation>
    </message>
    <message>
        <source>D sharp</source>
        <translation></translation>
    </message>
    <message>
        <source>E flat</source>
        <translation></translation>
    </message>
    <message>
        <source>E</source>
        <translation></translation>
    </message>
    <message>
        <source>F flat</source>
        <translation></translation>
    </message>
    <message>
        <source>E sharp</source>
        <translation></translation>
    </message>
    <message>
        <source>F</source>
        <translation></translation>
    </message>
    <message>
        <source>F sharp</source>
        <translation></translation>
    </message>
    <message>
        <source>G flat</source>
        <translation></translation>
    </message>
    <message>
        <source>G</source>
        <translation></translation>
    </message>
    <message>
        <source>G sharp</source>
        <translation></translation>
    </message>
    <message>
        <source>A flat</source>
        <translation></translation>
    </message>
    <message>
        <source>A</source>
        <translation></translation>
    </message>
    <message>
        <source>A sharp</source>
        <translation></translation>
    </message>
    <message>
        <source>B flat</source>
        <translation></translation>
    </message>
    <message>
        <source>B</source>
        <translation></translation>
    </message>
    <message>
        <source>C flat</source>
        <translation></translation>
    </message>
</context>
<context>
    <name>Numbers</name>
    <message>
        <source>zero</source>
        <translation></translation>
    </message>
    <message>
        <source>one</source>
        <translation></translation>
    </message>
    <message>
        <source>two</source>
        <translation></translation>
    </message>
    <message>
        <source>three</source>
        <translation></translation>
    </message>
    <message>
        <source>four</source>
        <translation></translation>
    </message>
    <message>
        <source>five</source>
        <translation></translation>
    </message>
    <message>
        <source>six</source>
        <translation></translation>
    </message>
    <message>
        <source>seven</source>
        <translation></translation>
    </message>
    <message>
        <source>eight</source>
        <translation></translation>
    </message>
    <message>
        <source>nine</source>
        <translation></translation>
    </message>
    <message>
        <source>ten</source>
        <translation></translation>
    </message>
    <message>
        <source>eleven</source>
        <translation></translation>
    </message>
    <message>
        <source>twelve</source>
        <translation></translation>
    </message>
    <message>
        <source>thirteen</source>
        <translation></translation>
    </message>
    <message>
        <source>fourteen</source>
        <translation></translation>
    </message>
    <message>
        <source>fifteen</source>
        <translation></translation>
    </message>
    <message>
        <source>sixteen</source>
        <translation></translation>
    </message>
    <message>
        <source>seventeen</source>
        <translation></translation>
    </message>
    <message>
        <source>eighteen</source>
        <translation></translation>
    </message>
    <message>
        <source>nineteen</source>
        <translation></translation>
    </message>
    <message>
        <source>twenty</source>
        <translation></translation>
    </message>
</context>
<context>
    <name>Objects</name>
    <message>
        <source>banana</source>
        <translation></translation>
    </message>
    <message>
        <source>elephant</source>
        <translation></translation>
    </message>
    <message>
        <source>robot</source>
        <translation></translation>
    </message>
    <message>
        <source>flower</source>
        <translation></translation>
    </message>
    <message>
        <source>fish</source>
        <translation></translation>
    </message>
    <message>
        <source>rooster</source>
        <translation></translation>
    </message>
    <message>
        <source>airplane</source>
        <translation></translation>
    </message>
    <message>
        <source>candle</source>
        <translation></translation>
    </message>
    <message>
        <source>scissors</source>
        <translation></translation>
    </message>
    <message>
        <source>key</source>
        <translation></translation>
    </message>
    <message>
        <source>horse</source>
        <translation></translation>
    </message>
    <message>
        <source>dog</source>
        <translation></translation>
    </message>
    <message>
        <source>cat</source>
        <translation></translation>
    </message>
    <message>
        <source>camel</source>
        <translation></translation>
    </message>
    <message>
        <source>crocodile</source>
        <translation></translation>
    </message>
    <message>
        <source>pig</source>
        <translation></translation>
    </message>
    <message>
        <source>snake</source>
        <translation></translation>
    </message>
</context>
</TS>
